// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIAIrira-kC2aLb5P_5SC0B82eynwWTw',
    appId: '1:360208229070:web:aa6f7d018ad37ef461269f',
    messagingSenderId: '360208229070',
    projectId: 'sudafood',
    authDomain: 'sudafood.firebaseapp.com',
    storageBucket: 'sudafood.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBmDZjMpKk5krcHEC3tavf6wBlCOst1I8',
    appId: '1:360208229070:android:07e46590e2d0ee4b61269f',
    messagingSenderId: '360208229070',
    projectId: 'sudafood',
    storageBucket: 'sudafood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYbbTh9fwlGmMTmIsI1vYa4BlasiXbcpg',
    appId: '1:360208229070:ios:e1b2ced763c5d32961269f',
    messagingSenderId: '360208229070',
    projectId: 'sudafood',
    storageBucket: 'sudafood.firebasestorage.app',
    iosBundleId: 'com.sudafood.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYbbTh9fwlGmMTmIsI1vYa4BlasiXbcpg',
    appId: '1:360208229070:ios:df1501eea501605761269f',
    messagingSenderId: '360208229070',
    projectId: 'sudafood',
    storageBucket: 'sudafood.firebasestorage.app',
    iosBundleId: 'com.sudafood.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBIAIrira-kC2aLb5P_5SC0B82eynwWTw',
    appId: '1:360208229070:web:87219486ad33bc1a61269f',
    messagingSenderId: '360208229070',
    projectId: 'sudafood',
    authDomain: 'sudafood.firebaseapp.com',
    storageBucket: 'sudafood.firebasestorage.app',
  );
}
